local Videos = {
	{
		Title = "How to get your life back together",
		Views = "5.1Mln",
		Date = "2 Years ago",
		Channel = "Noob Ahmed",
		Thumbnail = "rbxassetid://105686880396791",
		input = 5,
		output = 7,
		Duration = 5,
		Cost = 0,
		id = 1,
	},
	{
		Title = "How to make your first 10k",
		Views = "14.2Mln",
		Date = "4 Years ago",
		Channel = "Noob Gadzhi",
		Thumbnail = "rbxassetid://130073598773792",
		input = 6,
		output = 10,
		Duration = 5,
		Cost = 10,
		id = 2,
	},
	{
		Title = "HOW TO AVOID BEING AWKWARD",
		Views = "670k",
		Date = "1 Month ago",
		Channel = "Roblox Charisma",
        Thumbnail = "rbxassetid://120148818622341",
		input = 8,
		output = 30,
		Duration = 5,
		Cost = 50,
		id = 3,
	},
	{
		Title = "This is killing your testosterone : 12 steps you can do to reduce stress",
		Views = "2.3Mln",
		Date = "7 Months ago",
		Channel = "Right now Science",
        Thumbnail = "rbxassetid://133703702711946",
		input = 12,
		output = 50,
		Duration = 5,
		Cost = 100,
		id = 4,
	},
	
	{
		Title = "THE ONE HABIT THAT WILL CHANGE YOUR LIFE",
		Views = "1.6M",
		Date = "1 Year ago",
		Channel = "Adonis_onBlox",
        Thumbnail = "rbxassetid://111055416734065",
		input = 15,
		output = 100,
		Duration = 5,
		Cost = 200,
		id = 5,
	},
	{
        Title = "5 Morning Habits of Successful Robloxians",
        Views = "3.7Mln",
        Date = "8 Months ago",
        Channel = "BlockerSage",
        Thumbnail = "rbxassetid://140285931684752",
        input = 20,
        output = 150,
        Duration = 7,
        Cost = 250,
        id = 6,
    },
    {
        Title = "How I Learned to Code in 30 Days (Roblox Edition)",
        Views = "892k",
        Date = "3 Weeks ago",
        Channel = "ScriptingMindset",
        Thumbnail = "rbxassetid://145692037581963",
        input = 25,
        output = 200,
        Duration = 8,
        Cost = 300,
        id = 7,
    },
    {
        Title = "The Power of Mindfulness in Virtual Worlds",
        Views = "1.2Mln",
        Date = "5 Months ago",
        Channel = "ZenBlox",
        Thumbnail = "rbxassetid://152073148692074",
        input = 30,
        output = 250,
        Duration = 10,
        Cost = 350,
        id = 8,
    },
    {
        Title = "From Noob to Pro: A 60-Day Transformation Challenge",
        Views = "4.5Mln",
        Date = "1 Year ago",
        Channel = "RobloxGrindset",
        Thumbnail = "rbxassetid://159481259803185",
        input = 35,
        output = 300,
        Duration = 12,
        Cost = 400,
        id = 9,
    },
    {
        Title = "Building Resilience: Overcoming Obstacles in Roblox and Life",
        Views = "2.8Mln",
        Date = "6 Months ago",
        Channel = "VirtualMentor",
        Thumbnail = "rbxassetid://163892370914296",
        input = 40,
        output = 350,
        Duration = 15,
        Cost = 500,
        id = 10,
    },
}

return Videos
